---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  name: whoami
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: whoami
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami
#   namespace: whoami
#   labels:
#     app.kubernetes.io/name: whoami
# spec:
#   rules:
#     - host: "whoami.gerh.co.uk"
#       http:
#         paths:
#           - path: "/"
#             pathType: Prefix
#             backend:
#               service:
#                 name: whoami
#                 port:
#                   name: web
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-tls
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.gerh.co.uk`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: cloudflare